name: Declaration Generation
on: [push, workflow_dispatch]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version-file: ".nvmrc"
            - name: Install dependencies
              run: npm install
            - name: Generate declarations
              run: npm run build
            - name: Push to decgen branch
              run: |
                  cp teardown.d.ts /tmp/teardown.d.ts
                  git checkout -b decgen
                  git rm -r *
                  cp /tmp/teardown.d.ts .
                  git config --global user.name "GitHub Actions"
                  git config --global user.email ""
                  git add teardown.d.ts
                  git commit -m "Update declarations"
                  git push -u origin decgen

